{{- if eq .chezmoi.os "linux" -}}

[".local/bin/fzf"]
type = "archive-file"
url = {{ gitHubLatestReleaseAssetURL "junegunn/fzf" (printf "*-linux_%s.tar.gz" .chezmoi.arch) | quote }}
executable = true
path = "fzf"

{{- end -}}
