{{- $os := .chezmoi.os -}}
{{- if eq $os "darwin" -}}
  {{- $os = "macos" -}}
{{- end -}}

[".local/bin/jq"]
type = "file"
url = "https://github.com/jqlang/jq/releases/latest/download/jq-{{ $os }}-{{ .chezmoi.arch }}"
executable = true
