set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'dracula/vim', { 'name': 'dracula' }
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

if &term =~ '256color'
  set t_ut=
  set termguicolors
endif

syntax enable
silent! colorscheme dracula
highlight LineNr guifg=gray ctermfg=gray

if &term =~ '256color'
  set t_ut=
  set termguicolors
endif

syntax enable
highlight LineNr guifg=gray ctermfg=gray

set mouse=""
set nowrap
set autoindent smartindent

set ruler number
set incsearch hlsearch

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2

set fileencodings=utf8,big5,gbk,latin1
